name: Release Pipeline

on:
  push: {}

permissions:
  contents: read

jobs:
  build-test-release:
    name: Build/Test/Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }

      - name: Restore
        run: dotnet restore .\src

      - name: Build
        run: dotnet build -c Release .\src --no-restore

      - name: Run Core.Tests
        run: dotnet test -c Release .\src\DevOpsDaysTasks.Core.Tests --no-build --logger html --results-directory TestResults-Core.Tests

      - name: Upload Core.Tests results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-Core.Tests
          path: TestResults-Core.Tests/
        if: ${{ always() }}

      - name: Run IntegrationTests
        run: dotnet test -c Release .\src\DevOpsDaysTasks.IntegrationTests --no-build --logger html --results-directory TestResults-IntegrationTests

      - name: Upload Core.Tests results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-IntegrationTests
          path: TestResults-IntegrationTests/
        if: ${{ always() }}

      # Problem: `Version` and `VersionName` is hardcoded
      - name: Publish Release
        run: dotnet publish -c Release src\DevOpsDaysTasks.UI -o DevOpsDaysTasks /p:Version=2.0.0 /p:VersionName=Bear

      # Problem: Where to get the external files from
      - name: Copy templates
        run: |
          mkdir DevOpsDaysTasks/Templates
          cp workshop_material\default-tasks.xml DevOpsDaysTasks/Templates

      - name: Copy help
        run: |
          mkdir DevOpsDaysTasks/Help
          cp workshop_material/Help.pdf DevOpsDaysTasks/Help

      # Problem: Cert (external file) and password hardcoded
      - name: Sign release
        run: .\scripts\sign.ps1 .\DevOpsDaysTasks\DevOpsDaysTasks.UI.exe -PfxFile .\workshop_material\devopsdays_tasks_codesign.pfx -PfxPassword Password

      # Problem: Only upload to pipeline not to GitHub Releases
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: DevOpsDaysTasks
          path: DevOpsDaysTasks

